apiVersion: vpc.tencentcloud.jet.crossplane.io/v1alpha1
kind: VPC
metadata:
  name: test-vpc
  labels:
    provider: crossplane-provider-jet-tencentcloud
    app: test
spec:
  forProvider:
    cidrBlock: 10.2.0.0/16
    name: test-crossplane