apiVersion: nodepool.tencentcloud.jet.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: test-nodepool
spec:
  forProvider:
    name: test-nodepool-crossplane
    clusterIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    maxSize: 5
    minSize: 1
    vpcIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    subnetIdsSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    retryPolicy: INCREMENTAL_INTERVALS
    enableAutoScale: true
    deleteKeepInstance: false
    autoScalingConfig:
      - instanceType: SA2.2XLARGE16
        systemDiskType: CLOUD_PREMIUM
        systemDiskSize: 50
        enhancedMonitorService: False
        enhancedSecurityService: False
        publicIpAssigned: false
        securityGroupIds:
          - sg-09c6ckwj
        passwordSecretRef:
          key: password
          name: test-cluster
          namespace: crossplane-system
        dataDisk:
          - diskType: CLOUD_PREMIUM
            diskSize: 50
            deleteWithInstance: true