---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: tencentcloud-config
  namespace: crossplane-system
  labels:
    app: crossplane-provider-tencentcloud
spec:
  image: harbor.internal.moqi.ai/mqdb/provider-tencentcloud-controller:v0.3.0
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-tencentcloud
  namespace: crossplane-system
spec:
  package: harbor.internal.moqi.ai/mqdb/provider-tencentcloud:v0.3.0
  controllerConfigRef:
    name: tencentcloud-config