---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: tencentcloud-config
  labels:
    app: crossplane-provider-tencentcloud
spec:
  image: harbor.internal.moqi.ai/mqdb/provider-tencentcloud-controller:v0.2
  imagePullPolicy: Always
  args: ["-d"]
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-provider-tencentcloud
spec:
  package: harbor.internal.moqi.ai/mqdb/provider-tencentcloud:v0.2
  controllerConfigRef:
    name: tencentcloud-config