apiVersion: kubernetes.tencentcloud.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: test-cluster-crossplane
  labels:
    provider: crossplane-provider-jet-tencentcloud
    app: test
spec:
  forProvider:
    clusterName: crossplane-test-cluster
    clusterDesc: test cluster description
    clusterMaxPodNum: 32
    clusterMaxServiceNum: 32
    clusterInternet: false
    clusterCidr: 172.16.0.0/16
    clusterVersion: 1.22.5
    vpcId: vpc-s1ei2nia
---
apiVersion: nodepool.tencentcloud.jet.crossplane.io/v1alpha1
kind: NodePool
metadata:
  name: test-nodepool
spec:
  forProvider:
    name: test-nodepool-crossplane
    clusterIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    maxSize: 5
    minSize: 1
    vpcId: vpc-s1ei2nia
    subnetIdsSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    retryPolicy: INCREMENTAL_INTERVALS
    enableAutoScale: true
    deleteKeepInstance: false
    autoScalingConfig:
      - instanceType: SA2.2XLARGE16
        systemDiskType: CLOUD_PREMIUM
        systemDiskSize: 50
        enhancedMonitorService: False
        enhancedSecurityService: False
        publicIpAssigned: false
        securityGroupIds:
          - sg-09c6ckwj
        passwordSecretRef:
          key: password
          name: test-cluster
          namespace: crossplane-system
        dataDisk:
          - diskType: CLOUD_PREMIUM
            diskSize: 50
            deleteWithInstance: true
---
apiVersion: clusterendpoint.tencentcloud.jet.crossplane.io/v1alpha1
kind: ClusterEndpoint
metadata:
  name: test-clusterendpoint
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    clusterIntranet: true
    clusterIntranetSubnetIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test






