apiVersion: clusterendpoint.tencentcloud.jet.crossplane.io/v1alpha1
kind: ClusterEndpoint
metadata:
  name: test-clusterendpoint
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test
    clusterIntranet: true
    clusterIntranetSubnetIdSelector:
      matchLabels:
        provider: crossplane-provider-jet-tencentcloud
        app: test